server:
  port: 8090
  servlet:
    context-path: /mvc

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mvc_recovery_evaluation?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456

  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

project:
  repository:
    path: D:\seu\code\temp